name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Run ESLint
        working-directory: ./web
        run: npm run lint

      - name: Run TypeScript type check
        working-directory: ./web
        run: npx tsc --noEmit

      - name: Run tests
        working-directory: ./web
        run: npm run test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: matrix.node-version == 20
        with:
          working-directory: ./web
          file: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: false

      - name: Build application
        working-directory: ./web
        run: npm run build

      - name: Upload build artifacts
        if: matrix.node-version == 20
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            web/.next/
            !web/.next/cache/
          retention-days: 7